"""enable extensions.

Revision ID: ee4bbd3a1bb0
Revises:
Create Date: 2023-03-11 21:35:52.998988

"""
from alembic import op
from alembic_utils.pg_extension import PGExtension

# revision identifiers, used by Alembic.
revision = "ee4bbd3a1bb0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_uuid_ossp = PGExtension(schema="public", signature="uuid-ossp")
    op.create_entity(public_uuid_ossp)  # type: ignore

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_uuid_ossp = PGExtension(schema="public", signature="uuid-ossp")
    op.drop_entity(public_uuid_ossp)  # type: ignore

    # ### end Alembic commands ###
